services:
  web:
    image: mono_app
    build:
      context: .
      dockerfile: Dockerfile
    # pull_policy: never
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      STAGE: "prod"
      PHX_HOST: "localhost"
      PHX_SERVER: "true" # Esto asegura que el servidor Phoenix se inicie
      PORT: 4000
    networks:
      - kafka_network
    depends_on:
      - db
      - kafka

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kafka_network
    ports:
      - "5432:5432"

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge

volumes:
  postgres_data:
