import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :mono_app, MonoAppWeb.Endpoint,
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  secret_key_base: System.get_env("SECRET_KEY_BASE"),
  root: ".",
  version: Application.spec(:mono_app, :vsn)

config :kafka_broker,
  brokers: [
    {System.get_env("KAFKA_HOST") || "kafka",
     String.to_integer(System.get_env("KAFKA_PORT") || "9092")}
  ]

config :mono_app, :kafka,
  host: System.get_env("KAFKA_HOST") || "kafka",
  port: String.to_integer(System.get_env("KAFKA_PORT") || "9092")

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: MonoApp.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
